const sectorImages = {
    aliminum: [
        { url: 'img/ref/ensotek-referanslari-dalan-kimya-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-linde-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-novartis-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-erc-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-plastay-kimya-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dystar-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-kimya-kimyevi-mad-san-ve-tic-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-setas-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ravaber-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kimflor-kimya-san-ve-tic-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-meltem-kimya-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-nedex-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-polikor-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-pf-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-nuh-kompozit-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-sodas-sodyum-sanayii-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bmcolor-250x250-1.jpg', alt: '' },
        { url: 'img/ref/matek-makina-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/unormak-min-250x250-1.png', alt: '' },
        { url: 'img/ref/ineva-250x250-1.png', alt: '' },
        { url: 'img/ref/motorsan-250x250-1.png', alt: '' },
        { url: 'img/ref/ensotek-referanslari-mmc-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-kayislari-250x250-1(2).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ara-makina-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-teksan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-korel-elektronik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-aero-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tarimar-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-simge-endustriyel-muh-san-ve-tic-ltd-sti-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-samsun-makina-sanayi-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ege-proses-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tei-tusas-motor-sanayii-as-250x250-1.jpg', alt: '' }
    ],

    Automobil: [
        { url: 'img/ref/Ensotek Referansları - Tofaş.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Petlas.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Pirelli.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Sumitomo.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Falken.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Dunlop.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Samavto.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Bekaert.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Componenta .jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kırpart.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Major SKT.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Karsan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Dikmen Otomotiv San. ve Tic. Ltd. Şti..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Anka.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Akkardan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Fmc Hydraulic.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Izgen.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - HWASEUNG.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Yıldız Pul.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Çelikyay.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - AYD.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kalkancı.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Uğurlu Glass Oto Camları.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Muammer Pırlanta Dingil Döküm .jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - MKS Mehmet Eren Otomotiv Teks. ve Tic Ltd. Şti..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Tekay .jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ho Won Otomotiv.jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
],

    Allgemein: [
        { url: 'img/ref/tubitak-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-betek-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-trakya-birlik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-pirelli-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-perfetti-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-marsa-yag-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tofas-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dr-oetker-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ulker-biskuvi-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-pinar-sut-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dimes-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-beypilic-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-koska-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-vivident-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-askale-cimento-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-limak-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-isdemir-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ipek-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ugur-derin-dondurucu-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-assan-aluminyum-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-borusan-mannesmann-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimpor-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-euas-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-sumitomo-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-hilton-avanos-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kombassan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-linde-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-panda-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-saray-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-yonca-yag-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-beta-tea-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-basf-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-yildiz-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-thy-doco-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-samavto-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kompen-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-nurol-teknoloji-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kayseri-seker-fabrikasi-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-hes-hacilar-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-erbosan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimsa-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bati-soke-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-arslan-aluminyum-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-seyitomer-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-pilsan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-festival-hali-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-toscelik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bati-anadolu-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimko-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-hascelik-group-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-karsan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-falken-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kuzu-grup-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-novartis-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-the-marmara-otel-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ilci-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-umran-boru-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-arcelik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-zentiva-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-turk-ytong-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tezcan-galvaniz-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-senpilic-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-petlas-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-noksel-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-mey-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-koruma-klor-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kalyon-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-green-park-hotels-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-global-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dunlop-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-zer-salca-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dogus-insaat-ve-ticaret-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cici-sut-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cengiz-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-atesoglu-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-aves-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-akcansa-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-adopen-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-kayislari-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-keskinoglu-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-er-demir-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dalan-kimya-250x250-1.jpg', alt: '' },
        { url: 'img/ref/yayla-agro-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/yigit-aku-250x250-1.png', alt: '' },
        { url: 'img/ref/baktat-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/billur-tuz-min-250x250-1.png', alt: '' },
        { url: 'img/ref/boycelik-metal-san-ve-tic-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/colgate-palmolive-min-250x250-1.png', alt: '' },
        { url: 'img/ref/saray-aluminyum-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-askale-cimento-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-adacal-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ado-mining-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bati-anadolu-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bati-soke-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-akcansa-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-celik-granul-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-votorantim-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-korel-elektronik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-vicat-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-jahon-invest-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ugur-beton-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ustyapi-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-set-cimento-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tekno-seramik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-turk-ytong-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/kar-group-250x250-1.jpg', alt: '' },
        { url: 'img/ref/yd-insaat-250x250-1.jpg', alt: '' },
        { url: 'img/ref/eczacibasi-vitra-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-sintek-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bozzetto-group-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tayf-kimya-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-teknokem-kimya-san-ve-tic-ltd-sti-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ara-makina-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/aref-sogutma-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ege-proses-250x250-1.png', alt: '' },
        { url: 'img/ref/makina-takim-250x250-1.png', alt: '' },
        { url: 'img/ref/matek-makina-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/unormak-min-250x250-1.png', alt: '' },
        { url: 'img/ref/ineva-250x250-1.png', alt: '' },
        { url: 'img/ref/motorsan-250x250-1.png', alt: '' },
        { url: 'img/ref/ensotek-referanslari-mmc-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-kayislari-250x250-1(2).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ara-makina-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-teksan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-korel-elektronik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-aero-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tarimar-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-simge-endustriyel-muh-san-ve-tic-ltd-sti-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-samsun-makina-sanayi-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ege-proses-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tei-tusas-motor-sanayii-as-250x250-1.jpg', alt: '' }
    ],
    chemie: [
        { url: 'img/ref/Ensotek Referansları -  Basf.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Koruma Klor.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  BETEK.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Gentaş Kimya.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Dalan Kimya.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - LİNDE.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Zentiva.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Novartis.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Eczacıbaşı.gif', alt: '' },
    { url: 'img/ref/Ensotek Referansları - ERC.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Plastay Kimya.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - DyStar.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kale Kimya Kimyevi Mad. San. ve Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Setaş.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ravaber.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Kimflor Kimya San. ve Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Meltem Kimya.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Nedex.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Polikor.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  PF.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Nuh Kompozit.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Sodaş Sodyum Sanayiİ A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - ASCHEM.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Bmcolor .jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - BOZZETTO GROUP.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - TAYF KİMYA.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Teknokem Kimya San. ve Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - VOLANT.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Vateks.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Uğur Selülöz Kimya.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Esa Kompozit.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Esen Mikronize Maden San. ve Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Veskim.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  İnci Kimya.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Vira Color Masterbatches.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Birleşik Akrilik San. ve Tic. Ltd. Şti..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - İskefe.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - DRACO.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Özbak Geri Dönüşüm.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - AKONİ KİMYA A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Sulfert Kimya.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Sel Sanayi.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Polimersan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Plastifay Kimya Endüstri.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Aydemir.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Alemdar.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Üçgen Pigment.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Kat Company.jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
],

    einkaufs: [
        { url: 'img/ref/Ensotek Referansları - The Marmara Otel.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Green Park Hotels.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Hilton Avanos.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Akbatı AVM.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Oryataş.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Turka Otelcilik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Mukarnas Hotel.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - ORION AVM.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Galleria AVM.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Meryan Otel.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kaya Hotels.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Acity.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Bayındır Hastanesi.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Capitol AVM.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Capacity.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kuzu Grup.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Tursoy Otelcilik.jpg', alt: '' },
    { url: 'img/ref/tubitak.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Richmond Pamukkale.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - IC Hotels.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kervansaray.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Özkaynak Falez Otel.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Worldmar AVM.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Starlight.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - TAI.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Çağdaş Pano.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - İltekno.jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
],


    energie: [
        { url: 'img/ref/Ensotek Referansları - Seyitömer.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Mutlu Akü.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Global Holding.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - EÜAŞ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Altaca Enerji.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Agesa.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Nurol Teknoloji.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kipaş Holding.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Özcan Mühendislik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Hamle İnşaat...jpg', alt: '' },
    { url: 'img/ref/Ensotek Mühendislik Referansları - TMS Soğutma.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Rast Enerji.jpg', alt: '' },
    { url: 'img/ref/Ensotek Arıtma Referansları - Burmek.jpg', alt: '' },
    { url: 'img/ref/Ensotek Arıtma Referansları - Lamda Proje.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Omka Yapı.jpg', alt: '' },
    { url: 'img/ref/Ensotek Arıtma Referansları - Orient Water Tech..jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
],

    essen: [
        { url: 'img/ref/Ensotek Referansları - Ülker Bisküvi.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Pınar Süt.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Dimes.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Perfetti .jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Vivident.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Panda.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Şenpiliç.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Keskinoğlu.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Beypiliç.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Saray Holding.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Koska.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Aves.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Trakya Birlik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kayseri Şeker Fabrikası.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - THY Doco.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Dr. Oetker.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Mey.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kılıç.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Yonca Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Belkıs Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Karam Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Trakya Yem ve Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Tüzünler Tarım.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Zer Salça.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Doğa.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Seç Salça.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ekiz Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Maybi.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Marsa Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Mes Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Doğuş Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Orpir Orman Ürünleri.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Dok Duru Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Salti Tuz.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Milkon Süt.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Seçer Tarım.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Saadet Gıda.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Robat Zagros Mıneral Water.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Sibaş Gıda.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Slava Süt.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Mudurnu.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Neşeli Sütçü.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Cici Süt.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Bolacalar Un ve Yem.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kospek Pekmez.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ay Nişasta...jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Alyans Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Altınyağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Berrak.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - ABC Salça.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - ASICO..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Balkan Süt.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Biscot.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ateşoğlu.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Azermaya.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Azra Bisküvi.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Beta Tea.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Güryağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Dimak Diren.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Halavet Gıda.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - JV Agromir.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Reyka Konserve.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kühne.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Pak Yağ.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Baycan Gıda.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kremel SA.jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
],

    kunst: [
        { url: 'img/ref/Ensotek Referansları - ADOPEN.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kompen.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Eryap Grup.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kale Kayışları.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Pilsan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Mutlusan Electric.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kayalar.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Tisan Mühendislik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Öz-Plas.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ecoplast.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Şekeroğlu.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kafaoğlu.jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
],
    maschinenbau: [
        { url: 'img/ref/tubitak-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-betek-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-trakya-birlik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-pirelli-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-perfetti-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-marsa-yag-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tofas-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dr-oetker-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ulker-biskuvi-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-pinar-sut-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dimes-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-beypilic-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-koska-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-vivident-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-askale-cimento-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-limak-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-isdemir-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ipek-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ugur-derin-dondurucu-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-assan-aluminyum-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-borusan-mannesmann-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimpor-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-euas-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-sumitomo-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-hilton-avanos-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kombassan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-linde-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-panda-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-saray-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-yonca-yag-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-beta-tea-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-basf-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-yildiz-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-thy-doco-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-samavto-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kompen-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-nurol-teknoloji-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kayseri-seker-fabrikasi-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-hes-hacilar-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-erbosan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimsa-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bati-soke-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-arslan-aluminyum-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-seyitomer-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-pilsan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-festival-hali-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-toscelik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bati-anadolu-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimko-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-hascelik-group-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-karsan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-falken-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kuzu-grup-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-novartis-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-the-marmara-otel-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ilci-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-umran-boru-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-arcelik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-zentiva-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-turk-ytong-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tezcan-galvaniz-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-senpilic-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-petlas-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-noksel-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-mey-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-koruma-klor-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kalyon-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-green-park-hotels-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-global-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dunlop-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-zer-salca-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dogus-insaat-ve-ticaret-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cici-sut-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cengiz-holding-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-atesoglu-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-aves-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-akcansa-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-adopen-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-kayislari-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-keskinoglu-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-er-demir-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-dalan-kimya-250x250-1.jpg', alt: '' },
        { url: 'img/ref/yayla-agro-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/yigit-aku-250x250-1.png', alt: '' },
        { url: 'img/ref/baktat-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/billur-tuz-min-250x250-1.png', alt: '' },
        { url: 'img/ref/boycelik-metal-san-ve-tic-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/colgate-palmolive-min-250x250-1.png', alt: '' },
        { url: 'img/ref/saray-aluminyum-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimsa-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-engin-group-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-lafarge-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-mmc-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-nuh-cimento-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-mass-cement-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-mardin-cimento-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-makina-takim-endustri-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kavsan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-konya-cimento-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimpor-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimko-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-cimentas-group-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-as-cimento-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-askale-cimento-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-adacal-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ado-mining-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bati-anadolu-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bati-soke-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-akcansa-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-celik-granul-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-votorantim-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-korel-elektronik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-vicat-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-jahon-invest-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ugur-beton-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ustyapi-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-set-cimento-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tekno-seramik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-turk-ytong-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/kar-group-250x250-1.jpg', alt: '' },
        { url: 'img/ref/yd-insaat-250x250-1.jpg', alt: '' },
        { url: 'img/ref/eczacibasi-vitra-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-sintek-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-bozzetto-group-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tayf-kimya-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-teknokem-kimya-san-ve-tic-ltd-sti-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ara-makina-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/aref-sogutma-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ege-proses-250x250-1.png', alt: '' },
        { url: 'img/ref/makina-takim-250x250-1.png', alt: '' },
        { url: 'img/ref/matek-makina-min-250x250-1.jpg', alt: '' },
        { url: 'img/ref/unormak-min-250x250-1.png', alt: '' },
        { url: 'img/ref/ineva-250x250-1.png', alt: '' },
        { url: 'img/ref/motorsan-250x250-1.png', alt: '' },
        { url: 'img/ref/ensotek-referanslari-mmc-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-kayislari-250x250-1(2).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ara-makina-250x250-1(1).jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-teksan-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-korel-elektronik-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-kale-aero-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tarimar-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-simge-endustriyel-muh-san-ve-tic-ltd-sti-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-samsun-makina-sanayi-as-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-ege-proses-250x250-1.jpg', alt: '' },
        { url: 'img/ref/ensotek-referanslari-tei-tusas-motor-sanayii-as-250x250-1.jpg', alt: '' }
    ],

    metall: [
        { url: 'img/ref/Ensotek Referansları -  İsdemir.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Er demir.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Hes Hacılar.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Assan Alüminyum.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Arslan Alüminyum.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Tosçelik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Boyçelik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Erbosan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Hasçelik Group.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Gentaş.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - GBS Gentaş.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Nexans.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Noksel .jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - BDC Bilecik Demir Çelik San. ve Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Borusan Mannesmann.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Tezcan Galvaniz.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - ADOPEN.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Erciyas.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Gedik Kaynak.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Silvan Sanayi A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Sıddık Kardeşler.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Tozmetal Ticaret ve Sanayi A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ümran Boru.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Can Metal.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Componenta .jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Moston.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Döktim.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Erkon.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Anka.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Akdaş Döküm.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Vit Makina..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Sertel Hırdavat.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Güney Çelik Hasır ve Demir Mamülleri San. Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Nuh Panel.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Pir-İnci İmalat Sanayi A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Nuhtel Makina San. ve Tic. Ltdi. Şti..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Meydan Makas.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Şahinler Metal.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Hatboru.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ayata Metal Endüstri Boru Profil.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Gimsan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Körfez Döküm.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Kale Saç.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Çokyaşar Tel Örme ve Dokuma .jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Erel Sert Krom.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Şefkat Metal Geri Dönüşümleri.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Önerler Makina.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ukinoks Mutfak Sistemleri.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Yayla Tav Tesisleri Metal Isıl İşlem.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  LLC.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - MMK Metalurji.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Hellenic.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ark Emre.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Yılkar Döküm.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Cihan Metal San. ve Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
],
    tekstil: [
        { url: 'img/ref/Ensotek Referansları -  Festival Halı.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Ipek.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Flokser Textile.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Yasin Kaplan Carpet.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Baydemirler.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Bahariye.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  COATS.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Poliday.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Turktex.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Isımak.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Mayderi Sanayi ve Ticaret A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Giptaş İplik San. Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Çelemler.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Şirikçioğlu Mencucat.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Usta Gipe Iplik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Tat Tekstil.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  İzober-Beşler.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Polyteks Taşdelen Group.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Korkmaz Tekstil.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Güven İplik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Serko Tekstil.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Aydın Örme.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  KFS Küçükçalık.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Karakoç Tekstil San. ve Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Ünal Sentetik Dokuma San. ve Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
],

    verpact: [
        { url: 'img/ref/Ensotek Referansları - Hayat Kağıt.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kartonsan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kombassan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kar-Yapı Tasarım A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Elif Plastik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Parteks.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Ersan Ambalaj ve Yalıtım San. Tic. A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Kayseri Stropor..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Sarten..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Amcor.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Stroton...jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Atak Ambalaj.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Muratlı Karton.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Işık.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları -  Ufuk Isı Cam.jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
],

   zement: [
    { url: 'img/ref/Ensotek Referansları - Türk Ytong.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Çimko.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Limak.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Çimsa.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Akçansa.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Aşkale Çimento.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - As Çimento.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Batı Anadolu.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Batı Söke.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Vıcat.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Votorantim.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Nuh Çimento.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Çimpor.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kale.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Konya Çimento.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ado Mining.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Adaçal.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Çelik Granül.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kutes.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Tarımar.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ugur Beton.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Üstyapı.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - MMC.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Çimentaş Group.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Tekno Seramik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Lafarge.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Mardin Çimento.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Mass Cement.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Seramiksan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kale Kayışları.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Sintek.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Set Çimento.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Simge Endüstriyel Müh. San. ve Tic. Ltd. Şti..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - TEI Tusaş Motor Sanayii A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Samsun Makina Sanayi A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ege Proses.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Encotherm.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kale Aero.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Engin Group.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Kavsan.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Ara Makina.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Korel Elektronik.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - TEKSAN.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Akyapak Metal.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - UAB KOMPRESORIU CENTRAS.jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Makina Takım Endüstri A.Ş..jpg', alt: '' },
    { url: 'img/ref/Ensotek Referansları - Jahon Invest.jpg', alt: '' },
    { url: 'img/ref/ensotek sertifika logolari ce - iso - cti - ukas - turkak.jpg', alt: '' }
]
}; 
